### PR TITLE
sys-libs/compiler-rt-sanitizers: Patch musl for 8.0.1

### PR DESCRIPTION
**Pull request by g3ngr33n**
- Patch musl compiler-rt-sanitizers-8.0.1

Package-Manager: Portage-2.3.76, Repoman-2.3.16

### CODE REVIEW

**Comment by g3ngr33n** [comment]
Not sure the problem is from my side, travis output : 

'virtual/pam'

Package recently masked

**Comment by anarchpenguin** [comment]
You can use what is in main tree, just set -libfuzzer -sanitize -xray

**Comment by g3ngr33n** [comment]
Thanks for the tips, look alright except the fstab header (introduced in the 8 branch)

> 'fstab.h' file not found
> #include <fstab.h>

And probably to comment too :

> const unsigned long __sanitizer_bufsiz = BUFSIZ;

**Comment by anarchpenguin** [comment]
Not sure why your even seeing the missing header, that block of code should not even be run. I Just compiled version 8 and 9 without any additional patches.

**Pull request closed without merging**
