### PR TITLE
dev-libs/libffi: add muslx32 support

### PR DESCRIPTION
**Pull request by matijaskala**

### CODE REVIEW

**Comment by blueness** [comment]
do you have a working muslx32 stage3?  i have not been supporting that.  if you have a working stage3 then i'll start supporting that and merge any muslx32 stuff, but until then, i really don't want to expand the scope of the overlay unnecessarily.

**Comment by matijaskala** [comment]
I have the stage, but recompiling mpfr breaks gcc.
Here's the link: https://drive.google.com/open?id=0B4Hf4-pIscS-RkVpajF6TWhwYW8

**Comment by matijaskala** [comment]
Here it is: https://drive.google.com/open?id=0B4Hf4-pIscS-RkVpajF6TWhwYW8

**Comment by lluixhi** [comment]
...why does mpfr break the stage?

Also @blueness, I noticed there's another unofficial musl overlay over here: https://github.com/orsonteodoro/muslx32

Maybe we could start merging them in?

**Comment by blueness** [comment]
@lluixhi We could merge it, but right now I'd like to get our overlay upstream/into the tree as much as possible.  Adding x32 support would complicate this.

**Comment by lluixhi** [comment]
Sounds good.

**Comment by blueness** [comment]
@matijaskala this looks more appropriate for the muslx32 overlay.

**Comment by matijaskala** [comment]
Thanks for the link to the overlay. It seems to already have a similar patch.
About mpfr ... gcc is segfaulting with native-compiled libmpfr, but with cross-compiled libmpfr it works fine.

**Comment by blueness** [comment]
@matijaskala   I'll take a look at it.  I am interested in supporting muslx32 but I am only mortal ;)  If there is a well maintained muslx32 overlay then it makes it possible for me to automate builds.

**Comment by lluixhi** [comment]
@blueness 
After looking over the overlay briefly, there seem to be several broken packages (mpfr has a file in it named `does_not_work`)

The last commit was in November.

And some of the patches appear to exist just for the purpose of letting crossdev build them, instead of actually patching a musl or x32 related flaw -- just FYI.

I can probably start looking into muslx32 in summer -- hopefully we can have more of the stuff in this overlay moved to the main tree, but they need to be reported to their respective projects upstream, and also compiled against glibc to check for breakage.

**Pull request closed without merging**
