### PR TITLE
cleanup some more ebuilds, work in progress

### PR DESCRIPTION
**Pull request by stefson**
todo list: 

- [x] app-admin/sudo does work well on amd64, it seems to fail with x86 and hardened. It seems reasonable to drop all keywords but x86 in that ebuild to discourage portage to pull it in if not needed.
- [x] ~~app-editors/nano-2.7.5 is the recent stable and fails to compile. We host 2.8.2 which is not in tree, and all unstable in tree versions compile just fine. I guess it is best to open a stablisation request on the gentoo bug tracker?~~ I'll open a stab. bug in the next days and open a new pull request once it is through. 
- [x] I don't know for what reason the gnome-session ebuild is here? ~~gentoo musl uses eudev, no idea if it is even possible to compile the systemd dependencies the ebuild wants to see.~~ I bumped it anyway, but not test compiled it. 
- [x] ~~net-dialup/ppp is pretty much broken. I will try to find patches for this, but if someone is willing to help me I'd appreciate it a lot.~~ Should be fixed.
- [x] ~~same goes for net-fs/samba. It needs a revbump to stable for sec. reasons mostly, so if someone feels like helping out with patches or informations how to get this one going again drop me a line.~~ Shoud be fixed.

### CODE REVIEW

**Comment by stefson** [comment]
@blueness t I think that's it for the most. Travis keeps on failing because the description (copied from portage tree) of sys-libs/slang is too long -_- 

I still could bump gnome-session to recent stable, but not test it because of its systemd dependencies. 

What shall be done about nano?

**Comment by lluixhi** [comment]
Thanks for this, the overlay needed it but I didn't really have the time to clean everything up lately.

**Comment by stefson** [comment]
@blueness I'm done with cleaning up! :-)

**Comment by blueness** [comment]
pushed

**Pull request closed without merging**
