### PR TITLE
Add sys-libs/libapparmor and sys-apps/apparmor

### PR DESCRIPTION
**Pull request by milkey-mouse**
`sys-libs/libapparmor`: `secure_getenv()` is only available from glibc. Borrow a [patch from Alpine](https://git.alpinelinux.org/cgit/aports/tree/testing/apparmor/0001-Add-missing-secure_getenv-and-scandirat-functions.patch) that adds a standalone version.
`sys-apps/apparmor`: Borrow `stdio_filebuf.h`, another glibc exclusive. It should be under the GCC Runtime Library Exception, but either way the package is GPL so I don't think it's "tainted."

### CODE REVIEW

**Comment by milkey-mouse** [comment]
Oh you gotta be kidding me. I refresh the page and #129 implements this. I think this is entirely redundant now, not sure.

**Comment by milkey-mouse** [comment]
And `firejail` too! These patches were developed completely independently; what a weird coincidence!

**Comment by blueness** [comment]
@milkey-mouse can you compare what you were proposing and what landed in the overlay as a double check?

**Comment by blueness** [comment]
actually i reverted the other one and pushed this.  what i like about your approach is that the patches were broken out by issue and not just one lump patch.  i hope you'll keep this up.

**Pull request closed without merging**
