### PR TITLE
dev-libs/glib-2.64.5: sync with tree

### PR DESCRIPTION
**Pull request by dflogeras**

### CODE REVIEW

**Comment by anarchpenguin** [comment]
Both eapply can be dropped and the patches can be added to PATCHES to have them applied. Please make the corrections and I will be happy to do a full review before I push it.

**Comment by dflogeras** [comment]
Sorry, just copied the patches from previous ::musl variations of the ebuild.  Corrected now

**Comment by anarchpenguin** [comment]
> Sorry, just copied the patches from previous ::musl variations of the ebuild. Corrected now

Thanks for updating, I will get it pushed here shortly. I should have pointed out the keywords should match only that of what is supported in musl, I will address that when I push tho.

**Comment by anarchpenguin** [comment]
Has been pushed. Please include a signed off line next time.

**Pull request closed without merging**
