### PR TITLE
Add chromium and firefox musl scripts from smaeul and jakeogh

### PR DESCRIPTION
**Pull request by Sharrisii**
As discussed at https://github.com/gentoo/musl/issues/262 ,
these scripts can be added and then further updated.
The fact that the gentoo/musl overlay is missing these and other (very important) browsers is an issue that should be solved. This could be a first step to help achieve this.

### CODE REVIEW

**Comment by spotlightishere** [comment]
If you use rust from smaeul as of the time of writing, you can compile the newer Firefox Quantum sources (i.e 72.0.2) as-is from gentoo stable without any patching. #277 is currently about having these patches integrated with upstream in parts as well. All works buttery smooth as well.

Is there an advantage to musl with Firefox 41 instead of the latest ESR releases?

**Comment by Sharrisii** [comment]
No, there is no advantage I know of. This script is known to work however, and having these scripts integrated would already be a step forward. Updating to newer version can happen afterwards

**Comment by stefson** [comment]
What is your aim with regards to the firefox ebuild? The in tree version should work just fine on amd64, only `--enable-elf-hack` is broken on arm. 

If you want to work on the chromium ebuild, you should merge them to a branch of your overlay and start working, maybe you want to open an issue here to chat with other users and to share your branch with them. You can also use your master branch, but this might prevent you from syncing your overlay and rebase if needed. 

In any case, none of the patches referenced in the ebuilds are present in your pullrequest, so there's nothing to work with as of now.

**Comment by Sharrisii** [comment]
Regarding the aim with regards to the firefox ebuild (as the in tree version should work just fine on amd64):
For TAZ, we are currently focused on 32-bit (amd64 is to be released later).
Besides that, the aim would also be to make it as easy as possible to use the script (in which I mean that no modifications are needed on the script, nor that additional things need to be downloaded like patches, ...). So basically, way simpler to use then the regular firefox ebuild.

**Comment by stefson** [comment]
you have to pull in dev-lang/rust from smaeul, and use the firefox-73.0 ebuild from the tree. 

only thing you have to customize for x86 is to pull in this hacky patch from alpine, to disable broken stackwalk: https://git.alpinelinux.org/aports/tree/testing/firefox/disable-moz-stackwalk.patch

**Comment by awilfox** [comment]
For full builds, you may also want to fix [WebRTC](https://code.foxkit.us/adelie/packages/raw/master/user/firefox-esr/webrtc-broken.patch), [breakpad](https://code.foxkit.us/adelie/packages/raw/master/user/firefox-esr/bad-google-code.patch), and [the sandbox](https://code.foxkit.us/adelie/packages/raw/master/user/firefox-esr/fix-seccomp-bpf.patch), unless these are already fixed in Gentoo.  I believe breakpad may be fixed upstream in 73, not sure.  (We use 68 ESR.)

**Comment by Sharrisii** [comment]
As discussed in the musl mailing list, it would be best to switch to version 68.5-esr (see https://code.foxkit.us/adelie/packages/tree/master/user/firefox-esr ) and basically make a gentoo-version of adelie's 68.5 version, also using code from jakeogh (see https://www.openwall.com/lists/musl/2020/02/15/7 )

Since the chromium musl version can't be updated using data from newer versions, perhaps the chromium ebuild can already be imlemented to Gentoo/musl though

**Comment by anarchpenguin** [comment]
Wow this makes absolutely no sense what so ever. ESR and ~arch both support musl when using smauel's overlay for rust.

**Comment by anarchpenguin** [comment]
I am unsure what the user is requesting, feel free to reopen if you decide you want an update chromium that you have fully tested. Firefox in the tree all work fine with smaeul's overlay for rust, might see about copying it back to musl overlay no promises

**Pull request closed without merging**
