### PR TITLE
dev-utils/cmocka: define uintptr_t if not defined

### PR DESCRIPTION
**Pull request by Necktwi**
define uintptr_t if UINTPTR_MAX is not defined.

Signed-off-by: Necktwi Ozfguah <necktwi@ferryfair.com>

### CODE REVIEW

**Comment by blueness** [comment]
this looks good to me so pushed.  did you send this upstream?

**Comment by Necktwi** [comment]
I have replaced `if !defined(_UINTPTR_T) && !defined(_UINTPTR_T_DEFINED)` with `UINTPTR_MAX`. Instead I should have  used `||`. Anyway, I shall just forward it to upstream and hear their comments.

**Comment by blueness** [comment]
if you should have used `||` would you please submit an update

**Comment by Necktwi** [comment]
But then the pull request should go into the main `gentoo` overlay as it becomes generic. But then if the upstream don't agree upon using `UINTPTR_MAX` then the patch should be explicit for `musl`. will get back to you once I hear from upstream. My previous patch for `groff` has been updated by the upstream, so later versions don't require that `-musl.patch`.

**Pull request closed without merging**
