### PR TITLE
Added: www-client/firefox-52.9.0

### PR DESCRIPTION
**Pull request by intc**

### CODE REVIEW

**Comment by arkamar** [comment]
Output of `pkgcheck scan --commits`:
```
www-client/firefox
  NonsolvableDepsInStable: version 52.9.0: nonsolvable depset(depend) keyword(~alpha) stable profile (default/linux/alpha/17.0) (5 total): solutions: [ >=media-libs/libvpx-1.5.0:0=[postproc] ]
  NonsolvableDepsInStable: version 52.9.0: nonsolvable depset(rdepend) keyword(~alpha) stable profile (default/linux/alpha/17.0) (5 total): solutions: [ >=media-libs/libvpx-1.5.0:0=[postproc] ]
  PotentialStable: version 52.9.0: slot(0), stabled arches: [ amd64, x86 ], potentials: [ ~alpha, ~arm, ~arm64, ~ia64, ~ppc, ~ppc64 ]
  UnknownUseFlags: version 52.9.0: unknown USE flags: 'custom-optimization', 'eme-free', 'gmp-autoupdate', 'gtk2', 'hwaccel', 'pgo', 'rust', 'system-cairo', 'system-harfbuzz', 'system-icu', 'system-jpeg', 'system-libevent', 'system-libvpx', 'system-sqlite'
  UnnecessaryManifest: unnecessary files in Manifest: [ 0002-Use-C99-math-isfinite.patch, 0007-gcc9_2_0-workaround.patch, 0008-gcc9_2_0_workaround_xpconnect.patch, disable-auto-update.policy.json, disable-hunspell_hooks.patch, disable-moz-stackwalk.patch, discard-x86-precision-musl.patch, firefox-52.9.0-blessings-TERM.patch, firefox-52.9.0.ebuild, fix-fortify-inline.patch, fix-fortify-system-wrappers.patch, fix-seccomp-bpf.patch, fix-stack-overflow.patch, fix-toolkit.patch, fix-tools.patch, gentoo-default-prefs.js-1, icon/firefox.desktop, mallinfo.patch, missing-header-s390x.patch, musl-pthread-setname.patch ]
```

**Comment by intc** [comment]
Don't know if there's anything I can do on the 1st 4 lines. Cleaning of not used patches can be done.

**Comment by intc** [comment]
Added metadata, removed unused patches and updated keywords.

**Comment by blueness** [comment]
is this ready to go?

**Comment by anarchpenguin** [comment]
> is this ready to go?

Do not add this to overlay, if they need a security infested build let them keep it in their local overlay

**Comment by blueness** [comment]
the latest version of firefox, as far as i know, is 72.0.0.1.  your version is ancient.  it may build on musl, but we cannot recommend its use.  can you try to update the fixes to the latest and resubmit.

thanks for your efforts, but i hope you understand, we really can't go back that far.

**Comment by anarchpenguin** [comment]
Firefox esr and testing in gentoo are already musl compliant. There is no reason to be using 52.x except you do not want the dep of nodejs. Please test what is made available by myself in the ::gentoo tree and report bugs against it.

**Comment by intc** [comment]
For my part it's not possible (in near or even far future) to work with versions which depend on Rust. But someone else of course can. and will, do it. Thanks and good luck!

**Comment by anarchpenguin** [comment]
> For my part it's not possible (in near or even far future) to work with versions which depend on Rust. But someone else of course can. and will, do it. Thanks and good luck!

Is compiling rust a problem or hat is holding you back? We have full rust support via smaeul's overlay, we are also working to support rust-bin packages for musl users via the overlay. Last I knew our rust developers in gentoo are working to bring support from smaeul's overlay to something that can be committed into ::gentoo. Please let me know what is holding you back with rust and I will help you any way that I can.

**Pull request closed without merging**
