### PR TITLE
sys-libs/musl: try to fix leaking of hosts cflags into cross-musl

### PR DESCRIPTION
**Pull request by stefson**
I added this code, as suggested per comment from https://bugs.gentoo.org/667126#c6 

```
 	# Make sure host make.conf doesn't pollute us
 	if is_crosscompile || tc-is-cross-compiler ; then
 		CHOST=${CTARGET} strip-unsupported-flags
 	fi
```

@blueness  Could you review this, and merge it to the overlay, for testing?

### CODE REVIEW

**Comment by blueness** [comment]
I'm okay with stripping unsupported compiler flags for cross compiling, but not native, which was suggested in bug 667126.  did you test this and did it fix your problem?

**Comment by stefson** [comment]
If I got it correctly, the patch for the ebuild fixes two things: 

* strip-unsupported-cflags in case of bootstrapping a cross compile toolchain (this is the reason for #667126)
* strip-unsupported-cflags in case of cross-emerging `sys-libs/musl`, is this what you mean by not not stripping native cflags? 

In any case: if we find a patch that you can agree to, I'm going to test it locally before it would be commited.

**Comment by blueness** [comment]
1) this patch would go into the main tree, not the overlay
2) did you test that it fixes the cross compile problems you mention?

**Comment by stefson** [comment]
I need a few days for testing, right now I'm not sure how to make the emerge-wrappers play nicely with the musl overlay.

**Comment by mjeveritt** [comment]
I'm not having any trouble building cross- toolchains with musl - is this a particular issue because of -march=native in your CFLAGS ?

**Comment by stefson** [comment]
I don't use -march=native at all, which makes this even more of a headscratcher.

**Comment by stefson** [comment]
@mjeveritt could you please tell me if you're able to use cross-emerge wrappers and to cross-compile `sys-libs/musl` itself with that? It is `emerge-armv7a-unknown-linux-muselabihf -av sys-libs/musl` for armv7a (my usecase)

**Comment by mjeveritt** [comment]
> @mjeveritt could you please tell me if you're able to use cross-emerge wrappers and to cross-compile `sys-libs/musl` itself with that? It is `emerge-armv7a-unknown-linux-muselabihf -av sys-libs/musl` for armv7a (my usecase)

You have to be super-careful with the wrappers, one of the two works, and one doesn't (I don't remember which order counts).
I have a working toolchain, and I'm happy to send you a working binpkg if that helps ..

**Comment by mjeveritt** [comment]
Try `armv7a-unknown-linux-musleabihf-emerge` instead.
For some reason I'm getting a weird error saying:
`emerge: there are no ebuilds to satisfy "sys-libs/musl" for /usr/armv7a-unknown-linux-musleabihf/`

**Comment by stefson** [comment]
this config does need the patch we're discussing: 

```
CHOST=armv7a-unknown-linux-musleabihf
CBUILD=x86_64-pc-linux-gnu
```

this config does **not** need the patch we're discussing: 

```CHOST=armv7a-unknown-linux-musleabihf
CBUILD=x86_64-gentoo-linux-musl
```

Or to make it more clear: with a glibc host and musl target, cflags are leaking into musl-cross env
and with a musl host and musl target, this doesn't happen. 

True for glibc-2.29-r2 and musl-1.1.23; with crossdev -S armv7a-unknown-linux-musleabihf (that's binutils 2.31.1-r6; kernel 4.14-r1*; libc 1.1.22; and gcc 8.3.0-r1* at the moment. *=from musl overlay)

bonus: `sys-libs/musl` fails to execute src_install when cross-emerged from the musl-chroot, but it doesn't when cross-emerged from the glibc-chroot. I suspect this line to be the cause: https://github.com/gentoo/gentoo/blob/master/sys-libs/musl/musl-1.1.22.ebuild#L95 , since patching L96 from 
` [[ -e "${D}"/lib/ld-musl-${arch}.so.1 ]] || die`
to
`[[ -e "${D}"/lib/ld-musl-armhf.so.1 ]] || die`
makes it work.

**Comment by mjeveritt** [comment]
Ping @trofi for thoughts?

**Comment by stefson** [comment]
Thanks for the offer, but I need to fix this to have the ability to create a rootfs from scratch. You might want to remove stale symlinks, the crossdev script tends to create a total mess, also with the world file. Both wrappers work just fine for me.

**Comment by stefson** [comment]
@blueness : I managed to update the kernel on my arm device and thus can give this a runtime testing, can you please merge the open pr? It's a bit of a mess right now, which I'm not really willing to hack around before going for an emerge -e world on the arm: #253 #256 #257

**Comment by stefson** [comment]
@blueness I extensivly tested the patched ebuild, bootstrapped two cross-compiler for arm successfully: one from amd64-glibc host and one from amd64-musl host. Also cross-emerged the ebuild itself to armv7a-musl, and emerged the binary within a fresh stage3. It has since been completly rebuilt via `emerge -e world` and it's just fine in my opinion. 

It's up to you if you're going to stream it to the tree or if you prefere the overlay. Please don't forget to close #667126 ; and please ping me if you need me to extend the patch to musl-1.1.23 and musl-9999, just in case.

**Comment by stefson** [comment]
I don't understand your comment - do you mean to refer to #260 ?

**Comment by stefson** [comment]
This isn't about any eclass. But please, if you're confident that the eclass is now moved to the tree, just remove it.

**Comment by blueness** [comment]
This fix cannot go into the overlay.  Do you want to create a pull request against the main gentoo tree and I'll merge it there.  I'm pretty sure it will not affect native builds, nor catalyst builds, but if it does, I'll have to back out of it.

**Comment by blueness** [comment]
I had to back out of this.  It makes no sense to set the CHOST to CTARGET if this is a cross compile.  Also, we don't want tc-is-cross-compiler().

**Comment by stefson** [comment]
please reopen then, both here and the initial bug.

**Comment by blueness** [comment]
Can you try just the following
```
is_crosscompile && strip-unsupported-flags
```

**Comment by stefson** [comment]
nope, that doesn't work: 

```
>>> Configuring source in /var/tmp/portage/cross-armv7a-unknown-linux-musleabihf/musl-1.1.22-r1/work/musl-1.1.22 ...
armv7a-unknown-linux-musleabihf-gcc
checking for C compiler... armv7a-unknown-linux-musleabihf-gcc
checking whether C compiler works... no; compiler output follows:
armv7a-unknown-linux-musleabihf-gcc: error: unrecognized -march target: znver1
armv7a-unknown-linux-musleabihf-gcc: note: valid arguments are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5t armv5e armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8-m.base armv8-m.main armv8-r iwmmxt iwmmxt2
armv7a-unknown-linux-musleabihf-gcc: error: missing argument to ‘-march=’
 * ERROR: cross-armv7a-unknown-linux-musleabihf/musl-1.1.22-r1::own failed (configure phase):
 *   (no error message)
```

**Comment by blueness** [comment]
I need to understand why it is correct to set `CHOST=${CTARGET}`  This seems like it will break at least on Canadian cross compiling, and possibly more.  See

https://stackoverflow.com/questions/5139403/whats-the-difference-of-configure-option-build-host-and-target

The take-away quote:
```
In a word, build the code on --build, run it on --host with --target architecture environment.
```

So while this might work in this specific case, it doesn't cover cross compiling in general.  I know this is what's used elsewhere in the tree, but it seems to be wrong there too.  Convince me otherwise.

**Comment by mjeveritt** [comment]
I asked advice from slyfox aka @trofi as to what approach was best, and he pointed me to the glibc ebuilds as examples. Obviously I'm not teaching the proverbial grandmother to suck eggs here, but I tried adding:
```
setup_flags() {
        # Make sure host make.conf doesn't pollute us
        if is_crosscompile || tc-is-cross-compiler ; then
                CHOST=${CTARGET} strip-unsupported-flags
        fi

        # Over-zealous CFLAGS can often cause problems.  What may work for one
        # person may not work for another.  To avoid a large influx of bugs
        # relating to failed builds, we strip most CFLAGS out to ensure as few
        # problems as possible.
        strip-flags
        strip-unsupported-flags
        filter-flags -m32 -m64 '-mabi=*'
}
```
and added:  ``setup_flags`` _after_ the ``just_headers`` tests in ``src_configure``, ``src_compile`` and ``src_install``

**Comment by blueness** [comment]
@mjeveritt I know where the code came from.  This doesn't mean it correct.  The question again is why are we setting `CHOST=${CTARGET}`?

**Comment by mjeveritt** [comment]
> @mjeveritt I know where the code came from. This doesn't mean it's correct. The question again is why are we setting `CHOST=${CTARGET}`?

I'm guessing its a limitation of the 'strip-unsupported-flags' function .. I'll dig in the source ..

I take your point that it's a hack rather than a bona-fide need ..

**Comment by blueness** [comment]
@mjeveritt Yeah, it looks like a hack to me.

**Comment by mjeveritt** [comment]
> @mjeveritt Yeah, it looks like a hack to me.

I'm suspecting something in https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/flag-o-matic.eclass#n431 currently .. but I'm drowning in variables at this point ..

**Comment by mjeveritt** [comment]
@blueness - my bet is at https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/flag-o-matic.eclass#n439 .. that's just not gonna work with cross-compile is it?!

**Comment by trofi** [comment]
glibc's ebuild summarises nicely what CTARGET actually means today for crosdev: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/glibc/glibc-2.30-r1.ebuild#n43

One day we will fix crossdev not to require cross-*/${libc} and hacks would not be needed anymore.

But that day is not today and we have to infer real CHOST from ${CATEGORY} than from make.conf:
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/glibc/glibc-2.30-r1.ebuild#n346

**Comment by blueness** [comment]
@trofi Thanks for the clarification Sergei.  I've put the fix back.

**Pull request closed without merging**
