### PR TITLE
net-libs/libtirpic: version bump to 1.0.2-r1

### PR DESCRIPTION
**Pull request by karlguy**
tested, everything works fine

### CODE REVIEW

**Comment by blueness** [comment]
1) please note that its not libtirpic but libtirpc
2) the in tree version =net-libs/libtirpc-1.0.2-r1 so i was going to remove this package
3) so does the in tree version =x11-libs/pixman-0.34.0 work

Can you explain why we need these on the overlay?

**Comment by karlguy** [comment]
@blueness 
> the in tree version =net-libs/libtirpc-1.0.2-r1 works so i was going to remove this package
The in tree does not work for me, that is why I made this. Said package did not compile on a fresh install after using the unmodified vanilla musl stage tarball distributed by you. Currently, I am not able to emerge -e, as the only package that fails is =net-libs/libtirpc-1.0.2-r1. This has nothing to do with clang or anything like that.

> so does the in tree version =x11-libs/pixman-0.34.0 work
Oops. It compiles with gcc, but not with clang. I guess this doesn't belong here then.

**Comment by blueness** [comment]
give me the steps to reproduce the problem with libtirpc.  i tried on both stage3-amd64-musl-hardened and stage3-i686-musl vanilla with no issues.

**Comment by blueness** [comment]
also can you give me the failure from the build log.

**Comment by karlguy** [comment]
the failure is just a "missing sys/queue.h"

**Comment by blueness** [comment]
okay i see what's going on here.  i had sys-libs/queue::musl installed.  its sufficient to add `elibc_musl? ( sys-libs/queue )` to DEPEND to get it to work.  is there any reason why we need this patch and can't just add the dependency?

**Comment by karlguy** [comment]
The only thing these patches do is allow it to be compiled with clang. The software has gcc extensions that clang doesn't support.

**Comment by blueness** [comment]
okay i've fixed this by adding the missing dep on sys-libs/queue.  if these packages (libtirpc and pixman) fail to build with clang, then its not a musl issue.  test on glibc, and open bugs in the main gentoo bugzilla.  thanks for looking at this!

**Pull request closed without merging**
