### PR TITLE
sys-auth/polkit: bump version to 0.115

### PR DESCRIPTION
**Pull request by SJLC**

### CODE REVIEW

**Comment by SJLC** [comment]
Hold off on this one -- turns out that a popup error dialog on lxde startup is being caused by polkitd dying with complaint
`Error relocating /usr/lib/libmozjs-52.so: _ZN2js16TlsPerThreadDataE: symbol not found`

**Comment by SJLC** [comment]
Apparently spidermonkey introduced this thread-local area in the recent upgrade, and it is causing a runtime error rather than a link error

```
readelf -s usr/lib/libmozjs-52.so | grep Tls | c++filt 
     1: 00000004     4 TLS     LOCAL  HIDDEN    17 js::TlsPerThreadData
```

Is there some secret to using thread-local storage with musl?

**Comment by SJLC** [comment]
Other libs on my system have "TLS GLOBAL DEFAULT" entries but not "TLS LOCAL HIDDEN" so the problem is likely the combination rather than thread-local in general

**Comment by blueness** [comment]
There's nothing special about TLS on musl, that I know of.   FYI, I built on a glibc system and the symbol is marked HIDDEN there too.  I'm not sure why.  I don't think you can link against a hidden symbol.

**Comment by blueness** [comment]
looks good to me.  i'm not sure why a hidden symbol is okay there on glibc but not musl, but exposing it is logically correct and works.

**Pull request closed without merging**
