### PR TITLE
cleanup some ebuilds

### PR DESCRIPTION
**Pull request by stefson**
I don't know why the checksum refresh of mesa gives me sha256 instead of blake2b

### CODE REVIEW

**Comment by lluixhi** [comment]
@stefson wait, what's the mesa problem exactly? am I applying the wrong patch?

**Comment by stefson** [comment]
The lines in the source code changed with 17.2.8, upstream added 'defined(__CYGWIN__)' in that line. I hope it doesn't break anything the way I fixed this?

**Comment by lluixhi** [comment]
Er well there's already a patch for the changed source code (mesa-17-musl_endian) so we could just change that.

Anyway, merging the rest of your changes in.

**Comment by stefson** [comment]
No idea what happened, but I'm fine either way. 

Would you consider to add 
'manifest-hashes = BLAKE2B SHA512'
to the layout.conf of the overlay?

**Pull request closed without merging**
