### PR TITLE
dev-lang/perl: add ebuild and musl memmem patch

### PR DESCRIPTION
**Pull request by 65278**
Perl 5.26.2 uses memmem if the symbol is defined in libc, but never sets _GNU_SOURCE when including string.h.
Since memmem is then implicitly declared, the result pointer is cut off after 32 bits, which causes all sorts of undefined behaviour.

I'm going to file a bug with perl, but it's basically a variant of this bug: https://rt.perl.org/Public/Bug/Display.html?id=128358

### CODE REVIEW

**Comment by blueness** [comment]
i'm afraid this might called a circular block when building stage3's with catalyst.  what are the risks if we don't address the bug and wait for upstream to catchup?  what i can do is add the patch to `/etc/portage/patches` in the stage3 directly, but that's ugly.

**Comment by 65278** [comment]
In core perl, It's hard to hit a codepath where this matters. Some functions only check if there was a result. There's one codepath through regexes that might be taken.
Filter::Util::Call does pointer arithmetic and reliably causes perl to say 'out of memory'.
So hard to say, any number of modules may be broken, but core perl <mostly> works

There's a different approach we can take. Perl ships an internal memmem() function called ninstr(), so we could rip out that part of perl. It would fix your stage3 problem, but at the cost of not using musls nicely engineered memmem.

**Comment by 65278** [comment]
Had another look at the issue. If we don't set _GNU_SOURCE, strlcat and strlcpy are also going to be subtly broken in perl. Pathtools::Cwd might break with ENAMETOOLONG, etc.pp.
So we'll need to patch that too if you don't take my inital patch.

**Comment by blueness** [comment]
FYI, I can set _GNU_SOURCE via an env var in the stage3 tarball.  But if we have to resort to patching for memmem, then we might as well patch for strlcat and strlcpy.  I'll wait for you to update this bug and then i'll add the patches to `/etc/portage/patches` in the stage3's.  So we won't need an ebuild for this.  Proceeding via `/etc/portage/patches` will avoid circular dependencies.  Thanks for working on this.

**Comment by stefson** [comment]
Is this the reason for `app-text/po4a` failing to compile since the update to perl-5.26?

**Comment by mjeveritt** [comment]
tagging @anarchpenguin here

**Comment by blueness** [comment]
this should be fixed in the tree.

**Pull request closed without merging**
