### PR TITLE
sys-auth/polkit: add polkit-0.118-r1 w/o spidermonkey dep and optiona…

### PR DESCRIPTION
**Pull request by vklimovs**
…l netgroup

Signed-off-by: Vjaceslavs Klimovs <vklimovs@gmail.com>

### CODE REVIEW

**Comment by anarchpenguin** [comment]
This is a no go as is. It will fail when it does not find mozjs

./configure: 19805: test: xyes: unexpected operator
checking for LIBJS... no
configure: error: Package requirements (mozjs-78) were not met:

**Comment by vklimovs** [comment]
Hey Jory,
I am having trouble reproducing this problem. I have two machines without spidermonkey installed, including the musl one for which this was done:

`fulcrum /var/tmp/portage/sys-auth/polkit-0.118-r1 # locate mozjs
/home/vklimovs/Projects/gentoo/dev-perl/JavaScript-SpiderMonkey/files/mozjs185.patch
/home/vklimovs/Projects/gentoo/media-gfx/freewrl/files/freewrl-1.22.13-mozjs187-config.patch
/home/vklimovs/Projects/gentoo/net-libs/libproxy/files/libproxy-0.4.15-mozjs-52-1.patch
/home/vklimovs/Projects/gentoo/net-libs/libproxy/files/libproxy-0.4.15-mozjs-52-2.patch
/var/db/repos/gentoo/dev-perl/JavaScript-SpiderMonkey/files/mozjs185.patch`

and ebuild compiles and installs fine. More so, ./files/polkit-0.118-duktape.patch clearly makes the check for mozjs-78 conditional:

`
fulcrum /var/tmp/portage/sys-auth/polkit-0.118-r1 # grep -R 'LIBJS' .
./files/polkit-0.118-duktape.patch:-PKG_CHECK_MODULES(LIBJS, `[mozjs-78])
...`

`
+AC_ARG_WITH(duktape, AS_HELP_STRING([--with-duktape],[Use Duktape as javascript backend]),with_duktape=yes,with_duktape=no)
+AS_IF([test x${with_duktape} == xyes], [
+  PKG_CHECK_MODULES(LIBJS, [duktape >= 2.0.0 ])
+  AC_SUBST(LIBJS_CFLAGS)
+  AC_SUBST(LIBJS_LIBS)
+], [
+  PKG_CHECK_MODULES(LIBJS, [mozjs-78])
+
+  AC_SUBST(LIBJS_CFLAGS)
+  AC_SUBST(LIBJS_CXXFLAGS)
+  AC_SUBST(LIBJS_LIBS)
+])
+AM_CONDITIONAL(USE_DUKTAPE, [test x$with_duktape == xyes], [Using duktape as javascript engine library])
`

`./configure: 19805: test: xyes: unexpected operator`

Is interesting. Can that have something to do with it?

**Comment by anarchpenguin** [comment]
> Hey Jory,
> I am having trouble reproducing this problem. I have two machines without spidermonkey installed, including the musl one for which this was done:
> 
> `fulcrum /var/tmp/portage/sys-auth/polkit-0.118-r1 # locate mozjs /home/vklimovs/Projects/gentoo/dev-perl/JavaScript-SpiderMonkey/files/mozjs185.patch /home/vklimovs/Projects/gentoo/media-gfx/freewrl/files/freewrl-1.22.13-mozjs187-config.patch /home/vklimovs/Projects/gentoo/net-libs/libproxy/files/libproxy-0.4.15-mozjs-52-1.patch /home/vklimovs/Projects/gentoo/net-libs/libproxy/files/libproxy-0.4.15-mozjs-52-2.patch /var/db/repos/gentoo/dev-perl/JavaScript-SpiderMonkey/files/mozjs185.patch`
> 
> and ebuild compiles and installs fine. More so, ./files/polkit-0.118-duktape.patch clearly makes the check for mozjs-78 conditional:
> 
> `fulcrum /var/tmp/portage/sys-auth/polkit-0.118-r1 # grep -R 'LIBJS' . ./files/polkit-0.118-duktape.patch:-PKG_CHECK_MODULES(LIBJS,`[mozjs-78])
> ...`
> 
> `
> +AC_ARG_WITH(duktape, AS_HELP_STRING([--with-duktape],[Use Duktape as javascript backend]),with_duktape=yes,with_duktape=no)
> +AS_IF([test x${with_duktape} == xyes], [
> 
>     * PKG_CHECK_MODULES(LIBJS, [duktape >= 2.0.0 ])
> 
>     * AC_SUBST(LIBJS_CFLAGS)
> 
>     * AC_SUBST(LIBJS_LIBS)
>       +], [
> 
>     * PKG_CHECK_MODULES(LIBJS, [mozjs-78])
> 
>     * AC_SUBST(LIBJS_CFLAGS)
> 
>     * AC_SUBST(LIBJS_CXXFLAGS)
> 
>     * AC_SUBST(LIBJS_LIBS)
>       +])
>       +AM_CONDITIONAL(USE_DUKTAPE, [test x$with_duktape == xyes], [Using duktape as javascript engine library])
>       `
> 
> 
> `./configure: 19805: test: xyes: unexpected operator`
> 
> Is interesting. Can that have something to do with it?

I know what the unexpected operator fix is. I am also gonna review the ebuild again. I am sure I did not set duktape useflag which would expect spidermonkey to be installed. This is what will be expected by users as well, so it must be fixed for -duktape builds.

**Comment by anarchpenguin** [comment]
I have reworked to remove bashism from configure.ac. I have also added a duktape useflag which will ensure we only build against duktape if requested well still leaving spidermonkey support avaliable for those who wish to have it instead. Soon as I mirror the duktape patch via my devspace, I will push the modified ebuild and patch to the overlay. Thanks for being patient while I worked out a few issues with it.

**Comment by anarchpenguin** [comment]
I have pushed it. Sorry for not having it autoclosed.

**Pull request closed without merging**
