### PR TITLE
gcc fix for #583266

### PR DESCRIPTION
**Pull request by stefson**
This fixes an internal compile error on x86, which gets triggered by building firefox with debug symbols. I added the fix for the two gcc-4.9.x ebuilds which are in the overlay, but if you would rather see a -r100 ebuild please let me know. 

Right now I am using 4.8.5 on x86 which triggers some other compile failures, so I'd be happy to upgrade to gcc 4.9

### CODE REVIEW

**Comment by blueness** [comment]
I need to bring this in ~arch so can you prepare -r100's and drop all keywords to ~arch.  Also, please take a look at how to properly format the commit messages.  Just do a `git log` to see the style we've been using.

**Comment by stefson** [comment]
Sure, I will prepare a -r100 of gcc-4.9.4 only and drop the keywords accordingly. 

Can you please explain which "style" I should use for the commit messages?

**Comment by blueness** [comment]
Do a git log to see.
Line 1: <category>/<package>: short description, 72 chars wide max
Line 2: blank
Line3+: (optional) longer explanation, 80 chars wide max

sys-devel/gcc: bump to gcc-4.9.4, address bug #590098

**Comment by stefson** [comment]
Ok, I'll close this for now and prepare a new pull request.

**Pull request closed without merging**
