### PR TITLE
More overlay

### PR DESCRIPTION
**Pull request by necktwi**
Most of the patches are from various distributions like Alpine Linux and few are of my own after consulting #musl.

### CODE REVIEW

**Comment by blueness** [comment]
i'm sorry but you've got way too much in one PR for me to review this properly and there is one failure.  i know its a pita, but can you do one PR for each package you want to touch.  This makes reviewing and reverting (if necessary) much easier.  Also take a look at how commit messages are done and try to conform to the standard.  The musl overlay is now being used by several "mission critical" operations so we have to be disciplined about this.  Thanks for the work!

**Comment by stefson** [comment]
Is there a bug report for the openrc bug the patch fixes?

**Comment by necktwi** [comment]
@stefson, https://git.alpinelinux.org/aports/commit/?id=151e1484cbebe3b0824a90daea686a45f537a997 is the patch I borrowed :) I didn't find any bug report on it.
@blueness, sure, I'll provide a single ebuild per day. I just built a working `musl-gentoo` for my RPi3B(aarch64). This time I shall build for my RPi1B2(armv6j) :)
What is the ebuild thats failing? The fatals in travis-ci log are not related to any of the ebuilds I provided; may be they are the dependents.

**Comment by stefson** [comment]
@necktwi proof me wrong, but it seems this has been fixed at https://github.com/OpenRC/openrc/commit/a32b14bbb43e9888acaaea6f764fb8dcb34fb941

**Comment by necktwi** [comment]
I couldn't find it on google. I should start searching GitHub as well. Glad, OpenRC found that its using non-standard definition. Thank you!

**Comment by necktwi** [comment]
for aarch64 it compiled, however, one should not use the native arch flag as mentioned at https://wiki.gentoo.org/wiki/Raspberry_Pi/Minimal_musl%2Bbusybox_cross_building.

**Comment by stefson** [comment]
Indeed, crossdev pulls in the hosts CFLAGS, and thus fails. Is that a crossdev bug?

**Comment by necktwi** [comment]
I think so because it should specify the right CFLAGS for a target. but I don't know how crossdev compiles a cross toolchain.

**Comment by stefson** [comment]
is it still true that this part of the musl ebuild:
`[[ -e "${D}"/lib/ld-musl-${arch}.so.1 ]] || die` 

should be uncommented when emerging `sys-libs/musl` with the cross-emerge wrappers into `/usr/armv*/` ?

**Comment by stefson** [comment]
@blueness - openrc is fixed by https://github.com/gentoo/gentoo/commit/40cfe363037e94ce1053c98f59ecb6981b840e5f. You might want to mask the 0.40 branch to prevent broken stage3's, in case it ever goes stable before 0.41?

**Comment by blueness** [comment]
@stefson i'm testing openrc now.  try to keep the threads clean.  so open a separate ticket for each issue

@necktwi are you planning on cutting this up into separate commits?

**Comment by necktwi** [comment]
@blueness yes I will do it. I just got occupied with graphics drivers but I will make this one a priority.

**Comment by blueness** [comment]
@necktwi please break this up into individual PR's against packages.  There's a lot of cruft in there like backup packages ending in ~ and a lot of patch conflicts.  Right now your branch has just become too messy to work with.

**Comment by necktwi** [comment]
I am reverifying the ebuilds by building armv6j-unknown-linux-musleabihf cross-root. will submit a PR soon today.

**Pull request closed without merging**
