### PR TITLE
x11-libs/vte: in tree branch 2.91 works

### PR DESCRIPTION
**Pull request by stefson**
from version 44.2 on, there are no additional patches needed.

### CODE REVIEW

**Comment by stefson** [comment]
It was not really my intention to inherit the dosfstools commit into this pullrequest, it seems as if it got added automatically as I pushed it to the master branch.

**Comment by doughdemon** [comment]
Please update also the `metadata.xml` for dosfstools. Then this pull request should be good to be merged.

In future, to avoid having unrelated commits on your pull request, please use a new branch based of origin master for every pull request.

**Comment by stefson** [comment]
Fair enough, I will work with branches in the future. The metadata and Manifest should be fixed now and ready to go.

**Comment by doughdemon** [comment]
Thanks for the fix.

Finally, please clean up the history by squashing together the two
dosfstools commits. Instructions:

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by stefson** [comment]
I tried, no idea if it worked?

**Comment by doughdemon** [comment]
It didn't quite work. Thanks for trying!

I've now merged these manually

**Comment by stefson** [comment]
The bugfix for dosfstools has been upstreamed half a year ago, so unless someone would like to see this fix in the maintree there is no need for opening a bug on the gentoo side.

**Comment by doughdemon** [comment]
There is already a bug report:

https://bugs.gentoo.org/show_bug.cgi?id=574654

**Pull request closed without merging**
