### PR TITLE
dev-libs/libevdev: 'const struct input_event' has no 'input-event-sec'

### PR DESCRIPTION
**Pull request by Necktwi**
borrowed the patch from https://lists.freedesktop.org/archives/input-tools/2020-March/001532.html

### CODE REVIEW

**Comment by anarchpenguin** [comment]
Can you explain why your hitting such a bug? I have tested with a completely stable arm64 and x86_64 machine and neither hit the bug your wanting to have fixed.

**Comment by Necktwi** [comment]
@anarchpenguin is it due to me merging it on android-gentoo-prefix?

**Comment by blueness** [comment]
Same problem as with your procps PR.

**Comment by anarchpenguin** [comment]
Please update your PR as requested, if you would like this merged into musl overlay. Closing until such time as changes are provided.

**Pull request closed without merging**
