### PR TITLE
net-libs/webkit-gtk: reintroduce package synced with ::gentoo

### PR DESCRIPTION
**Pull request by arkamar**
It takes a little bit longer than I thought to accept https://github.com/gentoo/gentoo/pull/14120 to `::getnoo` but there are more people needing webkit on their musl boxes. Could we reintroduce it in `::musl` overaly again?

I will keep syncing this package with `::gentoo` until they accept https://github.com/gentoo/gentoo/pull/14120 PR.

### CODE REVIEW

**Comment by blueness** [comment]
pushed

**Comment by arkamar** [comment]
thanks

**Comment by arkamar** [comment]
Hmmm, I just pulled `master` and I cannot see my change in there.

**Comment by anarchpenguin** [comment]
> It takes a little bit longer than I thought to accept [gentoo/gentoo#14120](https://github.com/gentoo/gentoo/pull/14120) to `::getnoo` but there are more people needing webkit on their musl boxes. Could we reintroduce it in `::musl` overaly again?
> 
> I will keep syncing this package with `::gentoo` until they accept [gentoo/gentoo#14120](https://github.com/gentoo/gentoo/pull/14120) PR.

When adding ebuilds straight to stable please use -S instead of force.

**Comment by arkamar** [comment]
> When adding ebuilds straight to stable please use -S instead of force.

Ok, thanks. I will.

**Pull request closed without merging**
