### PR TITLE
media-libs/mesa: increased stacksize to prevent segfaults

### PR DESCRIPTION
**Pull request by callmetango**
* increased stacksize to prevent segfaults as suggested by https://github.com/alpinelinux/aports/pull/4847

I apply the pull request mentioned above and tested it for a week now. Mesa and Firefox are as stable as I can wish for. Could this be the solution for #136? Please test yourself.

### CODE REVIEW

**Comment by blueness** [comment]
Has anyone else tested this?  I'd like to apply it.

**Comment by blueness** [comment]
I pushed this, but we have moved on to mesa 18.1.9.  Do you know if that version addresses this issue?

**Comment by ronchaine** [comment]
I am facing the same old issues after updating to 18.1.9.  So most likely not.

**Comment by blueness** [comment]
can somone forward port this to 18.1.9-r1 and test.  if it works, make a pr an i'll apply asap.  i know this was submitted aug 25, but i was hoping it would make it upstream by magic --- and by magic i mean someone at alpine would have submitted the patch to the mesa folks.

**Comment by callmetango** [comment]
> can somone forward port this to 18.1.9-r1 and test. if it works, make a pr an i'll apply asap. i know this was submitted aug 25, but i was hoping it would make it upstream by magic --- and by magic i mean someone at alpine would have submitted the patch to the mesa folks.

The [mesa-18-musl-larger-stacksize.patch](https://github.com/gentoo/musl/blob/4a236c1806c62e93f66357ea6422369edec82b77/media-libs/mesa/files/mesa-18-musl-larger-stacksize.patch) is still needed and applicable up to [Mesa 18.2.3](https://gitlab.freedesktop.org/mesa/mesa/tags/mesa-18.2.3) as there was no change in the upstream code in [include/c11/threads_posix.h#L280](https://gitlab.freedesktop.org/mesa/mesa/blob/d219361b/include/c11/threads_posix.h#L280).

Ps. As said in https://github.com/gentoo/musl/issues/136#issuecomment-427645844 this patch is just a workaround for something bigger that needs to be fixed upstream.

**Comment by callmetango** [comment]
@blueness Forward ported the patch to Mesa 18.1.9-r1. I used this patched version for a while so "works on my machine." ;-)

**Comment by blueness** [comment]
i don't know what happened, but when i merged this i only got 18.1.6-r1 so i forward ported it to 18.1.9-r1

**Pull request merged**
