### PR TITLE
Glib 2.56 fix

### PR DESCRIPTION
**Pull request by g3ngr33n**

### CODE REVIEW

**Comment by g3ngr33n** [comment]
Will try later to fix the travis check

**Comment by blueness** [comment]
its probably not the fault of this pacakge.

**Comment by g3ngr33n** [comment]
will emerge repoman and check the ebuild

**Comment by g3ngr33n** [comment]
Alright :)

**Comment by blueness** [comment]
I'm sorry but this has become something of a mess.  I can't merge this:

1) Each PR should address one and only one package.  In this case, you should only touch glib.

2) The log message should conform to previous log messages.  In this case
```dev-libs/glib: fix version 2.56```

3) Squash all your "playing around" into one clean commit

4) Use `repoman` to test that the package doesn't have an QA issues.  First run `repoman full` to get any reports and then run `repoman commit` to actually commit.  `repoman` will automatically prompt you with a nice first line to the commit message.

5) If you're going to worry about making travis happy, make each package that you are going to touch its own PR.

I recommend you look at previous commits as a model.

**Comment by g3ngr33n** [comment]
Alright, will PR in a clean way. I must start by mesa without bellagio, as long mesa isn't merged any PR shall fail

**Pull request closed without merging**
