### PR TITLE
net-libs/webkit-gtk: sync with upstream

### PR DESCRIPTION
**Pull request by arkamar**
The ebuild synced with upstream.

Package-Manager: Portage-2.3.62, Repoman-2.3.11
Signed-off-by: Petr Vaněk <arkamar@atlas.cz>

### CODE REVIEW

**Comment by blueness** [comment]
ping me when this is ready if your still working on it.  thanks!

**Comment by arkamar** [comment]
I think it is ready, both `2.22.6` and `2.24.0` works for me. I am not sure about one thing, `KEYWORDS` are synced with upstream, that makes `2.22.6` stable for `x86` and `amd64`.

**Comment by blueness** [comment]
i dropped keywords for aches which are not supported on musl.  i'm okay with setting stable on 2.22.6 if its stable upstream and you tested.

**Comment by arkamar** [comment]
ok, thanks.

**Pull request closed without merging**
