### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by stefson**
This is for doing a test run at the moment, to see wether the fixes work. I will ping a maintainer if done. 

Please also allow eapi=7 in travis scripts!

### CODE REVIEW

**Comment by blueness** [comment]
you can put [DO NOT MERGE] in title and then remove it and ping me when its ready.  thanks.

**Comment by stefson** [comment]
@blueness - dev-libs/ell is responsible for the last critical error; so how can we get rid of this eapi 7 problem? In any case, the pullrequest can be merged.

**Comment by blueness** [comment]
i'm sorry i'm a getting a conflict.  can you rebase this.

**Comment by stefson** [comment]
more informations please, I cannot see that conflict?

**Comment by stefson** [comment]
like this? :o

**Comment by blueness** [comment]
Since the problem is `dev-games/irrlicht` maybe you can just drop it.

**Comment by stefson** [comment]
thing is I can't see this problem on github

**Comment by stefson** [comment]
closed, see #151

**Pull request closed without merging**
