### PR TITLE
Update libdrm requirements.

### PR DESCRIPTION
**Pull request by Uramekus**
https://packages.gentoo.org/packages/x11-libs/libdrm uses 2.4.75 as minimal since 12 Mar 2017

### CODE REVIEW

**Comment by blueness** [comment]
the manifest is broken.  can you check things at your end.

**Comment by blueness** [comment]
@lluixhi you just bumped mesa to 17.0.3 yesterday, can you comment on this pull requests, i don't want it to conflict with what you did.

**Comment by lluixhi** [comment]
Both libdrm-2.4.75 and libdrm-2.4.76 work, so we only have to drop libdrm from this repository.

It's unnecessary to modify the mesa ebuilds because we don't have any versions of libdrm earlier than 2.4.75 after deleting 2.4.65-r99. (And I'd rather we keep the differences between our ebuilds and those in ::gentoo to musl-specific patches because it makes upstreaming easier, when we get around to it..)

**Comment by blueness** [comment]
@Uramekus can you please clean up those pull requests

**Comment by Uramekus** [comment]
im back, guess you cant work well with Github web version.

how can i properly revert this noise/these things?

**Comment by Uramekus** [comment]
will close and open a clean PR, best method to not fuck up things, hard reversing didnt work for me.

**Pull request closed without merging**
