### PR TITLE
fixes for mesa

### PR DESCRIPTION
**Pull request by stefson**
reboot of 89c1adfdef658652e452c76a8b98931e4a2cf131

I'm actually clueless about meson, therefore I used the old autoconf ebuild for the revbump. It has been runtime tested successfully for vlc, firefox and lxde-terminal.

### CODE REVIEW

**Comment by blueness** [comment]
i'm not touching mesa until the following is fixed https://bugs.freedesktop.org/show_bug.cgi?id=35268

**Comment by stefson** [comment]
So, we will stick to mesa-18.1 branch then?

**Comment by blueness** [comment]
one way or another, this issue has to be fixed before moving past 18.1.

**Comment by stefson** [comment]
Is it correct that mesa-18.1 depends on <=llvm:6 but won't work with llvm:7, as the ebuilds of 18.1.6/9 suggests it?

**Comment by blueness** [comment]
I don't know.  If you want to work on this, ask ncopa from alpine what they're doing about this issue.

**Comment by blueness** [comment]
I have forward ported the fixes that Jory Pratt added.  Please test and open an issue if they don't work.

**Pull request closed without merging**
