### PR TITLE
add btrfs-progs

### PR DESCRIPTION
**Pull request by karlguy**

### CODE REVIEW

**Comment by lluixhi** [comment]
@karlguy libtirpc-1.0.2-r1 already includes that patch..

**Comment by karlguy** [comment]
Which patch? It wouldn't compile unless I added both of these patches.

**Comment by karlguy** [comment]
Reverted for now, it seems like it was getting miscompiled

**Comment by karlguy** [comment]
Is this going to be merged?

**Comment by blueness** [comment]
@karlguy I thought there was a compile problem?  Is this good to go as it?  I haven't tested.

**Comment by karlguy** [comment]
@blueness I reverted the libtirpc changes that I was experimenting with. I didn't realize github pull requests transparently added commits you make without you telling it to. :/

**Comment by blueness** [comment]
i squashed the commits before pushing

**Pull request closed without merging**
