### PR TITLE
cleanup some ebuilds, work in progress

### PR DESCRIPTION
**Pull request by stefson**

### CODE REVIEW

**Comment by stefson** [comment]
There is some more stuff on my todo list, but these seem to be the most important ones in my opinion. 

Is it okay to delete portage-2.3.5 in the overlay?

**Comment by blueness** [comment]
@stefson  yeah you can delete portage too.  keep each cleanup as its own commit since we want to be able to revert if something breaks.

**Comment by blueness** [comment]
@stefson should i wait for you to add the portage commit, or push this one now?

**Comment by stefson** [comment]
I am doing all the easy stuff at the moment and am going to ping you if I am finished with that, okay? But it would be a great help if you could checkout this bug for hunspell and validate if it is fixed: https://bugs.gentoo.org/show_bug.cgi?id=545502 I don't get any file collisions anymore with recent hunspell-1.6.1-r1 from tree?

**Comment by blueness** [comment]
@stefson yeah ping me.

**Comment by stefson** [comment]
@blueness it is good to go for now. I still have stuff on my to do list, but this will take longer and I am uncertain if I can find time for this in the next days. 

But, do you happen to know the people from the toolchain team? It would be so easy to merge the patch from https://github.com/gentoo/musl/pull/56 into the patch tarball, and therefore into the main tree. They are assigned to the gentoo bug about this, but no reaction so fare?

**Comment by blueness** [comment]
@stefson I'm on the toolchain team.  i think there's a bug open in bugs.g.o about it.  maybe ping me on that and i'll add it to our patchset.

**Comment by blueness** [comment]
pushed, please fix any errors travis-ci catches

**Pull request closed without merging**
