### PR TITLE
sys-libs/compiler-rt-sanitizers: fix building with clang on musl

### PR DESCRIPTION
**Pull request by 0181532686cf4a31163be0bf3e6bb6732bf**
Original ebuild taken from `::gentoo`, added few patches

### CODE REVIEW

**Comment by lyssdod** [comment]
Same PR in main tree: https://github.com/gentoo/gentoo/pull/21535

**Comment by stefson** [comment]
* I think something is wrong with the dir structure, it should resemble the gentoo tree. 
* Also you're only adding version 12.0.0, why are there llvmorg-10.x and llvmorg-11.x in the Manifest file? 
* In the meantime, there was an update to 12.0.1_rc4 with python-3.10 support, it would be helpfull to pull that in, instead of the rc1+rc2.

**Comment by lyssdod** [comment]
@stefson I've updated the structure and added `12.0.1_rc4`, but it's hard masked for me now:

```
$ eix -e compiler-rt-sanitizers
[I] sys-libs/compiler-rt-sanitizers
     Available versions:  
     (10.0.1) 10.0.1-r1^t
     (11.1.0) 11.1.0-r1^t
     (12.0.0) 12.0.0^t
     (12.0.1) **12.0.1_rc4^t **12.0.1.9999*l^t
     (13.0.0) **13.0.0.9999*l^t
       {+asan +cfi +clang +dfsan +gwp-asan +hwasan +libfuzzer +lsan +memprof +msan +profile +safestack +sanitize +scudo +shadowcallstack test +tsan +ubsan +xray ELIBC="glibc"}
     Installed versions:  12.0.0(12.0.0)^t(12:23:36 07/05/21)(asan cfi clang dfsan gwp-asan hwasan libfuzzer lsan memprof msan profile safestack scudo tsan ubsan xray -shadowcallstack -test ELIBC="-glibc")
     Homepage:            https://llvm.org/
     Description:         Compiler runtime libraries for clang (sanitizers & xray)
```

**Comment by stefson** [comment]
there will be llvm-12.0.1 final soon, if you add the rc4 now its easier to migrate the ebuild once the final is released. 

do you mind to tell on which arch you have tested the patches?

**Comment by lyssdod** [comment]
I see... I was testing on amd64

**Comment by stefson** [comment]
* so llvm-12.0.1 was released today, if you wait a few days you can resync 12.0.1-rc4 from the in tree version and this should be ok. 
* I personally would be happy to have backlinks to the original pullrequest of the patches, that makes it easier to keep track of them and possibly resync if needed to. you can for instance add the links as a comment into the ebuild. 
* Last but not least, for hygenic reasons please squash all commits into one final commit, once your work is finished.

**Comment by lyssdod** [comment]
okay, thanks!

**Pull request closed without merging**
