### PR TITLE
sys-auth/elogind: strndupa

### PR DESCRIPTION
**Pull request by Necktwi**
strndupa definition is added to src/test/test-hexdecoct.c.
better to just fix it rather removing the test.

Signed-off-by: Necktwi Ozfguah <necktwi@ferryfair.com>

### CODE REVIEW

**Comment by blueness** [comment]
I was waiting for this to happen :(  Can you please open a bug on bugs.gentoo.org and link this one.  assign the bug to asturm@gentoo.org and kensington@gentoo.org.  The easy way to do this is to add the patch contingent on `elibc_musl?` but the proper way is to add a check to `configure.ac` for `strndupa` and then use and `#ifdef MISSING_STRNDUPA` to include your definition.  Let's see what asturm and kensington have to say, how they want to proceed.  I can add the `configure.ac` check etc, but that means having to `eautoreconf` the whole package.  In the mean time, I'll add this to the musl overlay.  But we're moving in the wrong direction here --- we're trying to empty out the overlay.

**Comment by blueness** [comment]
I just tested elogind from the tree and it *builds* fine.  So am I correct in assuming that this is only for tests?

**Comment by Necktwi** [comment]
I never enabled tests on purpose; I don't even know how to enable them. These last four pull requests I've submitted are from the huge pull request I've submitted initially if you remember. the ebuild I've submitted now(234.4) seems very old. maybe the newer ebuild has rightly separated tests from the default emerge.

**Comment by blueness** [comment]
okay this is old.  i don't see a need to keep it in the musl tree.  i'm going to remove it.

**Pull request closed without merging**
