### PR TITLE
Adding/version bumping multiple ebuilds

### PR DESCRIPTION
**Pull request by Keepco**
Hello,
this PR contains some ebuilds I added/version bumped during the setup of my musl install. 

Some notes:
Libvirt: Building against libtirpc fixes the build for me. [1]
Glib: Applications like pavucontrol,paprefs wouldn't start with the glib ebuild currently provided in this ebuild

Please tell me if this PR is too big, I'll split it up then.
[1] https://github.com/voidlinux/void-packages/blob/d19eefb899eb023fc7d8ae28860579f5ba690f56/srcpkgs/libvirt/template

### CODE REVIEW

**Comment by lluixhi** [comment]
One request, could you remove the sessreg commit? sessreg needs to be sync'd and cleaned up anyway.

**Comment by Keepco** [comment]
Thanks for looking through it. I also added an mpd ebuild, as mpd would segfault with the default one

**Comment by lluixhi** [comment]
How did you get mpd to segfault? I'm using it right now and I didn't run into anything :P

**Comment by Keepco** [comment]
Oh wow, nvm that then, seems like it wasn't the patch that actually fixed it, but the rebuild, just tried it again. Dunno what changed tho

**Comment by lluixhi** [comment]
Alright, this can be closed then.

**Pull request closed without merging**
