### PR TITLE
sys-apps/systemd-tmpfiles: Added, with patch to remove selinux mallinfo lines

### PR DESCRIPTION
**Pull request by jpds**
Not sure if this belongs here or in the main repo, but I needed to apply the `systemd-tmpfiles-246-musl-mallinfo.patch` file on an selinux system of mine to make this compile.

### CODE REVIEW

**Comment by gyakovlev** [comment]
hey, I maintain systemd-tmpfiles in ::gentoo and would prefer patches in main repo, not here.
can you submit this PR to main repo please? also a bit of details why it's needed will be nice, just for the record.

**Comment by gyakovlev** [comment]
just @gyakovlev me on main repo once you open it, I'll test and merge.

**Comment by gyakovlev** [comment]
also fyi, added version `248.3` to gentoo, check it as well if you can =)
it has musl patchset, but I'm still testing the package, so it's unkeyworded.

**Comment by anarchpenguin** [comment]
> also fyi, added version `248.3` to gentoo, check it as well if you can =)
> it has musl patchset, but I'm still testing the package, so it's unkeyworded.

Is this still an issue or has it been addressed in ::gentoo already.

**Comment by mjeveritt** [comment]
https://bugs.gentoo.org/766833 also.

**Comment by mjeveritt** [comment]
https://github.com/gentoo/gentoo/blob/master/sys-apps/systemd-tmpfiles/systemd-tmpfiles-246.ebuild#L57
https://github.com/gentoo/gentoo/blob/master/sys-apps/systemd-tmpfiles/systemd-tmpfiles-248.3.ebuild#L63
lgtm

**Comment by gyakovlev** [comment]
I did not merge any PRs in ::gentoo.
I've tested 248.3, it works even on ppc64be-musl.

> https://bugs.gentoo.org/766833 also.
how is this relevant? It has been merged long time ago.

**Comment by gyakovlev** [comment]
@mjeveritt can you please stop creating noise?
do you realize I'm the maintainer of `systemd-tmpfiles` and I port the patchset myself and I test it on musl, and I'm in favor having patches in gentoo?

**Comment by mjeveritt** [comment]
> @mjeveritt can you please stop creating noise?
> do you realize I'm the maintainer of `systemd-tmpfiles` and I port the patchset myself and I test it on musl, and I'm in favor having patches in gentoo?

Then you can authoritatively answer Jory's question,  instead of bickering to me about it?

The OP states there was a problem with .246 which was RESO:FIXED by the bug I stated, Ergo the issue is closed, finished end-of, right?

Take your passive-aggressive tone elsewhere. Thank you.

**Comment by gyakovlev** [comment]
I did answer the question. Haven't heard from @jpds, did not merge anything from them and I don't have selinux system to test it myself.
I do know some selinux users though, `systemd-tmpfiles` works for them.

no, bug you've linked is about`reallocarray`  and not the issue being discussed here. so it's a complete miss.

**Comment by mjeveritt** [comment]
> I did answer the question. Haven't heard from @jpds, did not merge anything from them and I don't have selinux system to test it myself.
> I do know some selinux users though, `systemd-tmpfiles` works for them.
> 
> no, bug you've linked is about`reallocarray` and not the issue being discussed here. so it's a complete miss.

Pardon me, I thought I noticed in the diff this .. https://github.com/gentoo/musl/pull/433/files#diff-19f827b85626f031754d9b409b358a646d211dac7de064f05fad5d6787242fd3 .. let me ask you - does that not contain 'reallocarray' ?

**Comment by gyakovlev** [comment]
it's a copy of a patch already in the tree. @jpds is just copying it.
the patch sumbitted here is https://github.com/gentoo/musl/pull/433/files#diff-4246972f199e74303631c7eaba4b4bcc2200787ecf657d50f4fe0f83dbe8b83e

**Comment by gyakovlev** [comment]
@jpds I merged the patch to the tree blindly, trusting you.
let me know if `248.3` need is, as I can't really test. it will be stabilized soon.

**Pull request closed without merging**
