### PR TITLE
sys-apps/watchdog

### PR DESCRIPTION
**Pull request by nemunaire**
Fixes with upstream patches and a custom patch to avoid a dependency.

### CODE REVIEW

**Comment by doughdemon** [comment]
Could you open a bug on gentoo bugzilla?
I've just sent a different patch upstream for the bool_t problem: https://sourceforge.net/p/watchdog/patches/11/

**Comment by nemunaire** [comment]
I opened the bug https://bugs.gentoo.org/show_bug.cgi?id=604260.

Thanks for your nicer patch upstream! I've updated my pull request to integrate it.

**Comment by blueness** [comment]
If these patches has been accepted upstream, then we can add this directly to the tree and not the overlay.  It looks to me like they have been.  @nemunaire is that correct?

**Comment by blueness** [comment]
@nemunaire actually, sorry to be a bother, but if these are accepted upstream, let make the pull requrest against the tree and i'll apply it there.  Thanks!

**Comment by blueness** [comment]
@nemunaire sorry i just realized that there is some customized patches

**Pull request merged**
