### PR TITLE
x11-libs/libdrm: stable for arm and ppc

### PR DESCRIPTION
**Pull request by stefson**
I got it pulled in from tree by accident on my arm box.

### CODE REVIEW

**Comment by blueness** [comment]
did you really test on ppc?  the reason i ask is because ppc-musl is old and has problems.  do you have an updated version of a chroot or stage3 tarball?  if so, i wouldn't mind getting it because i want to start support ppc-musl again.

**Comment by stefson** [comment]
No, I didn't test ppc, just synced the keywords with those from tree.

**Comment by blueness** [comment]
okay, i'll push with ~ppc.  i do hope to one day resurrect it.

**Comment by blueness** [comment]
pushed, thanks.

**Comment by stefson** [comment]
You could ask smaeul if he has a more up to date rootfs for ppc, in any case he must at least have a cross compiler available as he needs them for linking the rust stages.

**Pull request closed without merging**
