### PR TITLE
x11-libs/xcb-util-image: Support for clang 3.9.0

### PR DESCRIPTION
**Pull request by waltercool**
Patch enabling compilation with clang 3.9.0, based on http://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-graphics/xorg-lib/xcb-util-image/clang.patch

### CODE REVIEW

**Comment by doughdemon** [comment]
Thanks for the patch. Why can't it be submitted to the main tree? I don't see why it should be musl specific.

**Comment by waltercool** [comment]
Just because my last time submitting things like that against main tree, I never got any answer because the maintainer never responded or no one else wanted to take a decision to merge because any "security" risk, and I don't know if this code would take any security risk or maky any mistake with GCC (I think Xorg supports C99 and above)

**Comment by doughdemon** [comment]
The patch in this pull-request looks harmless.

If you open a bug report with a build.log showing the compile failure,
and open a corresponding pull request with your patch, I don't think
that there will be a problem getting it merged in the main tree.

**Comment by waltercool** [comment]
Pull request submitted: https://github.com/gentoo/gentoo/pull/2496

**Comment by doughdemon** [comment]
Thanks!

**Comment by doughdemon** [comment]
This is a musl issue after all. Please try out the patched musl from gentoo/gentoo#2594 . (I tested locally. I could reproduce the bug but not with the patched musl.)

**Comment by blueness** [comment]
Yes please test with musl-1.1.15-r2.ebuild.

**Comment by waltercool** [comment]
Many thanks guys, let me test and I will notify you about the results. I will try to play a bit also with musl to validate that isn't breaking anything also.

**Comment by waltercool** [comment]
@doughdemon It compiled without problems, the problem was related to musl or did you made a custom patch on those musl functions? I mean, to notify xcb people.

I will be doing other compilation tests the next days, in case I have a problem I will notify you. I will close this issue because your commit solves it. Should I close it?

**Comment by doughdemon** [comment]
Thanks for testing!

Yes, please do write to the xcb list that it is not an issue on their
side.

The issue was that musl did not mark the function `__assert_fail`,
which is used in the implementation of `assert`, as `_Noreturn`.
Because of this, clang could not know that no code will be executed
after the `assert` statement. (except when `NDEBUG` is defined)
The upstream commit is here:

http://git.musl-libc.org/cgit/musl/commit/?id=e738b8cbe64b6dd3ed9f47b6d4cd7eb2c422b38d

**Comment by doughdemon** [comment]
Thanks for writing to the xcb list!

With sys-libs/musl-1.1.15-r2 being stable, this issue should be resolved. If not, please reopen.

**Pull request closed without merging**
