### PR TITLE
media-libs/mesa: sync with ::gentoo, drop old

### PR DESCRIPTION
**Pull request by arkamar**
I have synced ::gentoo mesa with musl tree and cleaned old 20.1.10 version.

### CODE REVIEW

**Comment by anarchpenguin** [comment]
current stable has already been sync'd.

**Comment by arkamar** [comment]
I don't see any update in this repository, maybe you forgot to push it?

**Comment by arkamar** [comment]
sorry to bother again, but `::gentoo` has `mesa-21.0.3` stable for 11 days now and we have `mesa-20.3.5` here. Could you reconsider this PR, please?

**Comment by mjeveritt** [comment]
> sorry to bother again, but `::gentoo` has `mesa-21.0.3` stable for 11 days now and we have `mesa-20.3.5` here. Could you reconsider this PR, please?

13adabf0 looks like it

**Pull request closed without merging**
