### PR TITLE
sys-apps/accountservice: sync with ::gentoo updates

### PR DESCRIPTION
**Pull request by vadorovsky**

### CODE REVIEW

**Comment by vadorovsky** [comment]
This, together with #480 (which we don't want merged here, I need to fix that upstream, but the workaround works for me ;) ), makes GNOME building and working.

**Comment by vadorovsky** [comment]
@alfredfo @thesamesam ping

**Comment by thesamesam** [comment]
> This, together with #480 (which we don't want merged here, I need to fix that upstream, but the workaround works for me ;) ), makes GNOME building and working.

To be clear, I didn't actually reject the PR. I just wanted you to explain how it fit with the upstream link I gave & whether you could send it upstream and include a link.

**Comment by vadorovsky** [comment]
> > This, together with #480 (which we don't want merged here, I need to fix that upstream, but the workaround works for me ;) ), makes GNOME building and working.
> 
> To be clear, I didn't actually reject the PR. I just wanted you to explain how it fit with the upstream link I gave & whether you could send it upstream and include a link.

Alright, sorry for misunderstanding. I replied there.

**Comment by vadorovsky** [comment]
Closing, it was done in https://github.com/gentoo/musl/commit/1509130765cbb849b2186954e0b24944eca843ee

**Pull request closed without merging**
