### PR TITLE
x11-base/xorg-server: revbump to 1.20.4

### PR DESCRIPTION
**Pull request by stefson**
arm is stuck at 1.20.3, please merge, thanks

### CODE REVIEW

**Comment by blueness** [comment]
Did you test this?

**Comment by stefson** [comment]
I had it queued, but then I questioned wether this is still needed and after some runtime testing it seems as if the patch and therefor the whole xorg-server files can be dropped from the overlay. The problem is, I can't remember for what reason this patch once got pulled in? Has it been for a compile failure, or to fix a more deeper issue that would require extensive testing? 

@doughdemon do you still use the arm port?

**Comment by doughdemon** [comment]
Without the patch, there is a compile failure for arm because of
missing declarations of out[bwl] and in[bwl].

I think musl provides these functions via `<sys/io.h>` for x86 and
amd64 but not arm.

**Comment by stefson** [comment]
Does x11-base/xorg-server::gentoo fail to compile for you? For me it doesn't, and runtime testing showed no issues?

**Comment by blueness** [comment]
Okay it sucks that we have to add this because its yet another package we have to maintain in the overlay.  The patch make complete sense though.  I've pushed it.

**Pull request closed without merging**
