### PR TITLE
Add dev-lang/go

### PR DESCRIPTION
**Pull request by aidanharris**
Following on from my comment in #89 here's a pull-request containing a bootstrap for go (dev-lang/go-bootstrap) and modified go ebuilds to use it. I'm not very experienced at writing ebuilds so feel free to suggest any improvements or shout at me if I'm doing something stupid...

To make reviewing easier I've attached a recursive diff below of the go ebuilds in the the main gentoo overlay and my small modifications to them.

```diff
diff -r /usr/portage/dev-lang/go/go-1.10.1.ebuild dev-lang/go/go-1.10.1.ebuild
52c52,53
< SRC_URI+="!gccgo? ( ${BOOTSTRAP_URI} )"
---
> 
> SRC_URI+="!gccgo? ( !bootstrap? ( ${BOOTSTRAP_URI} ) )"
59c60,65
< IUSE="gccgo"
---
> IUSE="bootstrap gccgo"
> 
> DEPEND="
> 	gccgo? ( >=sys-devel/gcc-5[go] )
> 	bootstrap? ( dev-lang/go-bootstrap )
> "
61d66
< DEPEND="gccgo? ( >=sys-devel/gcc-5[go] )"
163c168,178
< 	export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
---
> 	if use bootstrap
> 	then
> 		# Is there a better way to get the package version number?
> 		VERINS="$(best_version dev-lang/go-bootstrap)"
> 		VERINS="${VERINS/dev-lang\/go-bootstrap-/}"
> 		VERINS="${VERINS%.*}"
> 		export GOROOT_BOOTSTRAP="/usr/lib/go${VERINS}"
> 		[ ! -d "$GOROOT_BOOTSTRAP" ] && die "No such file or directory $GOROOT_BOOTSTRAP"
> 	else
> 		export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
> 	fi
diff -r /usr/portage/dev-lang/go/go-1.10.ebuild dev-lang/go/go-1.10.ebuild
52c52
< SRC_URI+="!gccgo? ( ${BOOTSTRAP_URI} )"
---
> SRC_URI+="!gccgo? ( !bootstrap? ( ${BOOTSTRAP_URI} ) )"
59c59
< IUSE="gccgo"
---
> IUSE="bootstrap gccgo"
61c61,64
< DEPEND="gccgo? ( >=sys-devel/gcc-5[go] )"
---
> DEPEND="
> 	gccgo? ( >=sys-devel/gcc-5[go] )
> 	bootstrap? ( dev-lang/go-bootstrap )
> "
163c166,176
< 	export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
---
> 	if use bootstrap
> 	then
> 		# Is there a better way to get the package version number?
> 		VERINS="$(best_version dev-lang/go-bootstrap)"
> 		VERINS="${VERINS/dev-lang\/go-bootstrap-/}"
> 		VERINS="${VERINS%.*}"
> 		export GOROOT_BOOTSTRAP="/usr/lib/go${VERINS}"
> 		[ ! -d "$GOROOT_BOOTSTRAP" ] && die "No such file or directory $GOROOT_BOOTSTRAP"
> 	else
> 		export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
> 	fi
Only in /usr/portage/dev-lang/go: go-1.9.1.ebuild
Only in /usr/portage/dev-lang/go: go-1.9.2.ebuild
Only in /usr/portage/dev-lang/go: go-1.9.3.ebuild
diff -r /usr/portage/dev-lang/go/go-1.9.4.ebuild dev-lang/go/go-1.9.4.ebuild
52c52
< SRC_URI+="!gccgo? ( ${BOOTSTRAP_URI} )"
---
> SRC_URI+="!gccgo? ( !bootstrap? ( ${BOOTSTRAP_URI} ) )"
59c59
< IUSE="gccgo"
---
> IUSE="bootstrap gccgo"
61c61,64
< DEPEND="gccgo? ( >=sys-devel/gcc-5[go] )"
---
> DEPEND="
> 	gccgo? ( >=sys-devel/gcc-5[go] )
> 	bootstrap? ( dev-lang/go-bootstrap )
> "
162c165,175
< 	export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
---
> 	if use bootstrap
> 	then
> 		# Is there a better way to get the package version number?
> 		VERINS="$(best_version dev-lang/go-bootstrap)"
> 		VERINS="${VERINS/dev-lang\/go-bootstrap-/}"
> 		VERINS="${VERINS%.*}"
> 		export GOROOT_BOOTSTRAP="/usr/lib/go${VERINS}"
> 		[ ! -d "$GOROOT_BOOTSTRAP" ] && die "No such file or directory $GOROOT_BOOTSTRAP"
> 	else
> 		export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
> 	fi
diff -r /usr/portage/dev-lang/go/go-9999.ebuild dev-lang/go/go-9999.ebuild
52c52
< SRC_URI+="!gccgo? ( ${BOOTSTRAP_URI} )"
---
> SRC_URI+="!gccgo? ( !bootstrap? ( ${BOOTSTRAP_URI} ) )"
59c59
< IUSE="gccgo"
---
> IUSE="bootstrap gccgo"
61c61,64
< DEPEND="gccgo? ( >=sys-devel/gcc-5[go] )"
---
> DEPEND="
> 	gccgo? ( >=sys-devel/gcc-5[go] )
> 	bootstrap? ( dev-lang/go-bootstrap )
> "
163c166,176
< 	export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
---
> 	if use bootstrap
> 	then
> 		# Is there a better way to get the package version number?
> 		VERINS="$(best_version dev-lang/go-bootstrap)"
> 		VERINS="${VERINS/dev-lang\/go-bootstrap-/}"
> 		VERINS="${VERINS%.*}"
> 		export GOROOT_BOOTSTRAP="/usr/lib/go${VERINS}"
> 		[ ! -d "$GOROOT_BOOTSTRAP" ] && die "No such file or directory $GOROOT_BOOTSTRAP"
> 	else
> 		export GOROOT_BOOTSTRAP="${WORKDIR}"/go-$(go_os)-$(go_arch)-bootstrap
> 	fi

```

### CODE REVIEW

**Comment by blueness** [comment]
If you have difficulties, let me know and maybe I can fix it up from where you leave off.

**Comment by parazyd** [comment]
@blueness Could this be handled in the portage tree with `elibc_musl` rather than needing the overlay? Whoever is building the bootstraps should find it easy to build go 1.4.3 as well.

**Comment by blueness** [comment]
@parazyd it probably does only need an `elibc_musl` check but I haven't tested.  If you want to propose something against the gentoo tree, I'd prefer that over the overlay which is growing too big.  The ideal is to get stuff from the overlay into the tree or upstream.

**Comment by parazyd** [comment]
On Wed, Apr 11, 2018 at 12:03:48PM +0000, Anthony G. Basile wrote:
>    [1]@parazyd it probably does only need an elibc_musl check but I
>    haven't tested. If you want to propose something against the gentoo
>    tree, I'd prefer that over the overlay which is growing too big. The
>    ideal is to get stuff from the overlay into the tree or upstream.

I should be able to come up with something, but it's up to the portage
maintainers to build a musl (or statically linked) golang 1.4.3
bootstrap tarball.

I have an ebuild here: https://github.com/parazyd/parlay/blob/master/dev-lang/go/go-1.10.1.ebuild

And as one can see it's only about having a correct bootstrap tarball.
Nothing else changes.

I'll stay in touch.

**Pull request closed without merging**
