### PR TITLE
app-admin/sudo: fix includes for id_t and mode_t

### PR DESCRIPTION
**Pull request by dlrobertson**
Patch submitted and accepted upstream.

Signed-off-by: Dan Robertson <dan@dlrobertson.com>

### CODE REVIEW

**Comment by dlrobertson** [comment]
Comments and critiques are welcomed! I'm a bit out of practice :smiley:

**Comment by stefson** [comment]
It would be great if you're able to get this merged upstream, that would save us from having to maintain another package in the overlay.

**Comment by dlrobertson** [comment]
> It would be great if you're able to get this merged upstream, that would save us from having to maintain another package in the overlay.

The patch has already been accepted upstream.

**Comment by stefson** [comment]
I see, it was more obvious if you did copy the git formated patch from github mirror. Is sudo-1.9.0 the only affected version?

**Comment by dlrobertson** [comment]
> I see, it was more obvious if you did copy the git formated patch from github mirror.

Ah, yeah good point.

>  Is sudo-1.9.0 the only affected version?

As far as I am aware 1.9.0 is the only version in portage that is affected.

**Comment by dlrobertson** [comment]
sudo 1.9.1 appears to be arriving soon https://github.com/sudo-project/sudo/commit/5a69831dd4398173bf9e0020c082f66129b37c63

I'll keep this PR open for now, but I think this PR should not be merged as 1.9.1 has this patch included and 1.9.0 is the only affected version.

**Comment by anarchpenguin** [comment]
https://bugs.gentoo.org/726720

Patches that have been applied upstream need to be applied in main tree for musl fixes. We have no reason to keep a package in the overlay that has been fixed upstream already.

**Pull request closed without merging**
