### PR TITLE
add ~amd64 keyword

### PR DESCRIPTION
**Pull request by DmitriyHetman**

### CODE REVIEW

**Comment by blueness** [comment]
This is not how keywords work.  What problem are you trying to fix?

**Comment by DmitriyHetman** [comment]
I use ~amd64 in make.conf, but main gentoo repository have a newer version of this lib, so portage trying to install it directly from gentoo repository, seems I fix it when allow ~amd64 only for overlays.
Also I can't install gcc6.1 from musl overlay, and I need to use musl-extras overlay to fix it, which have keywords.

**Comment by blueness** [comment]
your problem is how you set up your system, not the ebuild.  KEYWORD="amd64 ~amd64" is incorrect in an ebuild.

**Comment by DmitriyHetman** [comment]
OK, how to set up system with testing keyword? Overlays has high priority, but portage whatever installing from gentoo repository packages, which has newer versions in ::gentoo

**Comment by blueness** [comment]
don't run a ~amd64 system.  keyword individual packages using /etc/portage/package.accept_keywords.  you need to read the Gentoo Handbook, a bug report is not where you answer such a question.

**Pull request closed without merging**
