### PR TITLE
media-libs/openal: sync with the upstream.

### PR DESCRIPTION
**Pull request by arkamar**

### CODE REVIEW

**Comment by blueness** [comment]
pushed

**Comment by arkamar** [comment]
Hi Anthony,

On Fri, Jul 13, 2018 at 01:05:37PM -0700, Anthony G. Basile wrote:
> pushed

I don't see any of those two commits in master branch.

Petr

**Comment by blueness** [comment]
thanks for pointing that out.  i committed locally, but forgot to do `git push`.

**Comment by arkamar** [comment]
thanks

**Pull request closed without merging**
