### PR TITLE
x11-base/xorg-server: bump to v1.20.6

### PR DESCRIPTION
**Pull request by stefson**

### CODE REVIEW

**Comment by blueness** [comment]
pushed

**Comment by stefson** [comment]
@blueness this was a draft, wasn't it? The reason for that is, the old patch doesn't apply anymore, it needs to be re-elavuated.

**Comment by blueness** [comment]
@stefson i'm not sure.  should I back out?

**Comment by stefson** [comment]
I'm writing you from my rpi2, where I switched to =xorg-server-1.20.6::gentoo, and I can't see any problems. Also, I don't know why this patch was used for the last years, it's nowhere documented, no upstream link, no description, nothing. Really, it should be re-evaluated. 


    Am Samstag, 4. Januar 2020, 19:47:21 MEZ hat Anthony G. Basile <notifications@github.com> Folgendes geschrieben:  
 
 
@stefson i'm not sure. should I back out?

**Pull request closed without merging**
