### PR TITLE
some cleanup and revbumps

### PR DESCRIPTION
**Pull request by stefson**
ran into this recently.

### CODE REVIEW

**Comment by stefson** [comment]
I included a list of dependencies for the new xorg-server, as a preset for testing.

**Comment by blueness** [comment]
are you following the main tree as close as possible with these changes?

**Comment by stefson** [comment]
Do you want to keep the gcc-6.4.0, or what is your intention?

**Comment by blueness** [comment]
no i'm okay with removing 6.4.0, i am more interested in the bumps to mesa and xorg-server.  are you following the changes that were made in the gentoo tree?

**Comment by stefson** [comment]
Yes, these changes in the ebuilds themselves are taken from the main tree ebuilds. Apart from the dep-list file of course.

**Comment by stefson** [comment]
ah, wait a sec, I should push the mesa changes to the other ebuilds.

**Comment by blueness** [comment]
pushed

**Comment by blueness** [comment]
please fix the mesa issue a

**Comment by blueness** [comment]
okay pushed.  thanks for your contribution but keep in mind that this overlay is used in production by many groups.  try to be careful when contributing a PR.  if you want to experiment with a PR or suggest it and not have it committed right away, just say DO NOT MERGE YET.

**Pull request closed without merging**
