### PR TITLE
media-libs/mesa: openmax support removed

### PR DESCRIPTION
**Pull request by g3ngr33n**
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by g3ngr33n** [comment]
like this ?

**Comment by blueness** [comment]
This is better.  But why are we removing openmax support?

**Comment by g3ngr33n** [comment]
I could not find why but according to :

https://packages.gentoo.org/useflags/openmax
https://packages.gentoo.org/packages/media-libs/mesa

openmax has vanished from Gentoo, can't find it anymore in any profile. The error that travis showed in my PR was because of openmax

I'm still looking for the reason why it was removed from Gentoo, if you have hint...

**Comment by blueness** [comment]
okay that makes sense to remove it

**Comment by g3ngr33n** [comment]
https://forums.gentoo.org/viewtopic-p-8287280.html#8287280

I think it is safe to accept this PR

**Comment by blueness** [comment]
pushed

**Pull request closed without merging**
