### PR TITLE
rust and cargo fixes

### PR DESCRIPTION
**Pull request by stefson**
The rust _and_ cargo stages are linked against http-parser:0/2.6.2, right now there is no stage0 available linked against http-parser:0/2.8.0 - so for the moment, the rdep has to be locked. 

Also chost detection for arm is broken on 17.0 profile, the fix is from smaeul and it works as designed.

### CODE REVIEW

**Comment by stefson** [comment]
This is good to go, I'll copy new rust and cargo over when firefox-60.0 is out.

**Comment by blueness** [comment]
can you rebase this since it doesn't apply

**Comment by stefson** [comment]
I certainly can, where is the conflict? Here on github it gives me a thumbsup for not having any conflicts with the base branch.

**Comment by stefson** [comment]
Something is very wrong here. I tried to rebase on my own, but have no experience in it and failed, therefore I'll refork the overlay and redo the work in a new pr.

**Pull request closed without merging**
