### PR TITLE
Fix qtcore compile on libc++/libc++abi/clang

### PR DESCRIPTION
**Pull request by karlguy**
I added two use flags (libcxx, libcxxabi), which when turned on, allow qtcore to be compiled against these libraries. The libcxx flag depends on both clang and libcxx, and selects the linux-clang-libcxx profile in qtcore compilation, allowing it to compile on native clang systems linked against libcxx. The libcxxabi flag enables an additional patch that allows it to be linked against the libcxxabi library. When both of these flags are turned off, the package acts exactly the same as it did before, and compiles under gcc with no problems.

Sidenote: the eapply is in src_configure because when I put in in src_prepare, it broke some qt5-eclass preperation stuff

### CODE REVIEW

**Comment by blueness** [comment]
pushed.  please try to conform to our style of commit messages.  preface the description with the category/package where the change was made.  eg.
```dev-qt/qtcore: fix qtcore so it compiles with gcc```

**Comment by blueness** [comment]
i'm going to have to back out of this commit, it breaks the tree.  before committing, please run `repoman full` to make sure the dependencies work.

**Comment by karlguy** [comment]
ok, sorry about that

**Comment by blueness** [comment]
actually the libcxx stuff should go into the main tree.  the musl overlay should just add fixups for musl specific issues.

**Comment by karlguy** [comment]
ok sure

**Comment by karlguy** [comment]
@blueness 
I fixed it up, and put a patch here that can be applied to the main gentoo repo:
https://gist.github.com/karlguy/304644ea262e69a473ad559839898a89

I would make a proper github pull request, but I currently have an open pull request in the main gentoo repo.

**Comment by karlguy** [comment]
Nevermind, opened a pull request to the main repo.

**Pull request closed without merging**
