### PR TITLE
adds a fix for #590098

### PR DESCRIPTION
**Pull request by stefson**
This fixes compilation of media-libs/libraw on a musl profile @blueness

### CODE REVIEW

**Comment by stefson** [comment]
I'll open a new one to fix the Manifest

**Comment by blueness** [comment]
1) Can you give me the full reference to the upstream commit that addressed that bug
2) I'd rather get that into gcc-4.9.4, either into the official patchset for all of gentoo or into the overlay - I'll decide once I look at upstream's commit message

**Comment by stefson** [comment]
Actually I copied the patch over from gentoo #590098 , where you stated it looked good to you. So, I just tried to help out a bit with pushing it forward to the overlay. But I'm fine with adding it to 4.9.4 and skipping 4.9.3

**Comment by blueness** [comment]
It does look good but I'd like to push it out in the official gentoo patchset since I'm trying to decrease dependency on the overlay.  I can't just add an undocumented patch to the official patchset.  I'll bump gcc to 4.9.4 in the over and add it there then.

**Comment by stefson** [comment]
I'd really appreciate it as well to see gentoo bug #583266 getting fixed in a new gcc-4.9.4 ebuild. It is fixed by upstreams PR68470 , but they haven't addded the fix to the 4.9.x branch. If you wish to I can offer a backported patch, it needs a little adjustment.

**Pull request closed without merging**
